In [32]:
import numpy as np
##create arrays using numpy
##create a 1d array
arr1=np.array([1,2,3,4,5,6])
arr1.reshape(2,3)
print(arr1.shape)
print(arr1)
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5)   ## 1 row and 5 columns
arr2=np.array([[1,2,3,4,5],[2,3,4,5,5]])
print(arr2.shape)
print(arr2)

(6,)
[1 2 3 4 5 6]
(2, 5)
[[1 2 3 4 5]
 [2 3 4 5 5]]


In [3]:
import numpy as np
arr=np.arange(0,12,2)
print(f"{arr}\n")
arr=arr.reshape(2,3)
print(arr,"\n")
print(arr.shape)

[ 0  2  4  6  8 10]

[[ 0  2  4]
 [ 6  8 10]] 

(2, 3)


In [36]:
arr=np.ones((3,4))
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [9]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8],[6,10,11,12]])
print(arr[0:2,2:])
print(arr[0:2,1:3])

[[3 4]
 [7 8]]
[[2 3]
 [6 7]]


In [ ]:
import numpy as np